<?xml version='1.0' encoding='UTF-8'?>
<!--

    Copyright (c) OmniFaces
    All rights reserved.

    Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
    following conditions are met:

        * Redistributions of source code must retain the above copyright notice, this list of conditions and the
          following disclaimer.
        * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
          following disclaimer in the documentation and/or other materials provided with the distribution.
        * Neither the name of OmniFaces nor the names of its contributors may be used to endorse or promote products
          derived from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
    DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
    DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
    EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://vdldoc.omnifaces.org">
    <xs:element name="deprecated" type="xs:string" />
    <!-- vdldoc:deprecation is deprecated. It has been replaced by vdldoc:deprecated. -->
    <xs:element name="deprecation">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="deprecated" type="xs:string" maxOccurs="1" minOccurs="0" />
                <xs:element name="description" type="xs:string" maxOccurs="1" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="example-url" type="xs:anyURI" />
    <xs:element name="since" type="xs:string" />
    <xs:element name="el-variable">
        <xs:complexType>
            <xs:sequence>
            <xs:element name="el-variable-name" type="xs:string" maxOccurs="1" minOccurs="0" />
            <xs:element name="description" type="xs:string" maxOccurs="1" minOccurs="0" />
            <xs:element name="type" type="xs:string" maxOccurs="1" minOccurs="0" />
            <xs:element name="deprecated" type="xs:string" />
            <!-- vdldoc:deprecation is deprecated. It has been replaced by vdldoc:deprecated. -->
            <xs:element name="deprecation" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element type="xs:string" name="deprecated" maxOccurs="1" minOccurs="0" />
                        <xs:element type="xs:string" name="description" maxOccurs="1" minOccurs="0" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="example-url" type="xs:anyURI" maxOccurs="1" minOccurs="0" />
            <xs:element name="since" type="xs:string" maxOccurs="1" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>